features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://logo_1.png'
favicon:
  use_default: 0
  path: themes/custom/akbahai/images/favicon.ico
  mimetype: image/vnd.microsoft.icon
