enabled_fonts:
  1: 'https://www.google.com/webfonts/family?family=Archivo&subset=latin#regular'
  2: 'https://www.google.com/webfonts/family?family=Archivo&subset=latin#italic'
  3: 'https://www.google.com/webfonts/family?family=Archivo&subset=latin#600'
  4: 'https://www.google.com/webfonts/family?family=Charm&subset=latin#regular'
load_all_enabled_fonts: 1
_core:
  default_config_hash: r8uAx4mTBwCkgDFbdKCmhjgbb91BQ4HbWSYRKrlowMY
